spin_manifest_version = 2

[application]
name = "Spin"
version = "0.1.0"
authors = ["Andrew Steurer <andrew.steurer@fermyon.com>"]
description = ""

[[trigger.http]]
route = "/..."
component = "spin"

[variables]
access_key_id = { required = true, secret = true }
secret_access_key = { required = true, secret = true }
session_token = { required = true, secret = true }
bucket_name = { required = true }

[component.spin]
source = "main.wasm"
allowed_outbound_hosts = []

[component.spin.build]
#command = "tinygo build -target=wasi -gc=leaking -no-debug -o main.wasm main.go"
command = "GOOS=wasip1 GOARCH=wasm go build -o main.wasm main.go"
watch = ["**/*.go", "go.mod"]

[component.spin.variables]
access_key_id = "{{ access_key_id }}"
secret_access_key = "{{ secret_access_key }}"
session_token = "{{ session_token }}"
bucket_name = "{{ bucket_name }}"